=== NSSAC/EpiHiper-Schema/schema/diseaseModelSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Disease Model",
  "description": "The disease model describes the possible disease state changes within an individual including infection.",
  "type": "object",
  "required": [
    "states",
    "initialState",
    "infections",
    "transitions"
  ],
  "properties": {
    "states": {
      "type": "array",
      "description": "An array of states",
      "items": {
        "type": "object",
        "description": "A disease state",
        "required": [
          "id",
          "label",
          "susceptibility",
          "infectivity"
        ],
        "properties": {
          "id": {"$ref": "./typeRegistry.json#/definitions/uniqueId"},
          "label": {"$ref": "./typeRegistry.json#/definitions/label"},
          "susceptibility": {"$ref": "./typeRegistry.json#/definitions/nonNegativeNumber"},
          "infectivity": {"$ref": "./typeRegistry.json#/definitions/nonNegativeNumber"}
        }
      }
    },
    "initialState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
    "infections": {
      "type": "array",
      "description": "An array listing possible infections due to contact with other nodes.",
      "items": {
        "type": "object",
        "description": "An infection",
        "required": [
          "id",
          "label",
          "entryState",
          "exitState",
          "contactState",
          "transmissibility"
        ],
        "properties": {
          "id": {"$ref": "./typeRegistry.json#/definitions/uniqueId"},
          "label": {"$ref": "./typeRegistry.json#/definitions/label"},
          "entryState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
          "exitState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
          "contactState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
          "transmissibility": {"$ref": "./typeRegistry.json#/definitions/nonNegativeNumber"},
          "susceptibilityFactorOperation": {"$ref": "./typeRegistry.json#/definitions/numericOperation"},
          "infectivityFactorOperation": {"$ref": "./typeRegistry.json#/definitions/numericOperation"}
        }
      }
    },
    "transitions": {
      "type": "array",
      "description": "The transitions specifying the disease progression.",
      "items": {
        "type": "object",
        "description": "",
        "required": [
          "id",
          "label",
          "entryState",
          "exitState",
          "probability",
          "dwellTime"
        ],
        "properties": {
          "id": {"$ref": "./typeRegistry.json#/definitions/uniqueId"},
          "label": {"$ref": "./typeRegistry.json#/definitions/label"},
          "entryState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
          "exitState": {"$ref": "./typeRegistry.json#/definitions/uniqueIdRef"},
          "probability": {"$ref": "./typeRegistry.json#/definitions/nonNegativeNumber"},
          "dwellTime": {"$ref": "./typeRegistry.json#/definitions/distribution"},
          "susceptibilityFactorOperation": {"$ref": "./typeRegistry.json#/definitions/numericOperation"},
          "infectivityFactorOperation": {"$ref": "./typeRegistry.json#/definitions/numericOperation"}
        }
      }
    }
  }
}

=== NSSAC/EpiHiper-Schema/test/001/diseaseModelExample.json
{
  "$schema": "https://raw.githubusercontent.com/NSSAC/EpiHiper-Schema/master/schema/diseaseModelSchema.json",
  "states": [
    {
      "id": "susceptible",
      "label": "Susceptible",
      "susceptibility": 1.0,
      "infectivity": 0
    },
    {
      "id": "exposed",
      "label": "Exposed",
      "susceptibility": 0,
      "infectivity": 0
    },
    {
      "id": "infectious",
      "label": "Infectious",
      "susceptibility": 0,
      "infectivity": 0.1
    },
    {
      "id": "hospitalized",
      "label": "Hospitalized",
      "susceptibility": 0,
      "infectivity": 0.2
    },
    {
      "id": "funeral",
      "label": "Funeral",
      "susceptibility": 0,
      "infectivity": 0.2
    },
    {
      "id": "removed",
      "label": "Removed",
      "susceptibility": 0,
      "infectivity": 0
    }
  ],
  "initialState": "susceptible",
  "infections": [
    {
      "id": "contactWithInfectious",
      "label": "Susceptible -> Exposed {Infectious}",
      "entryState": "susceptible",
      "exitState": "exposed",
      "contactState": "infectious",
      "transmissibility": 1
    },
    {
      "id": "contactWithHospitalized",
      "label": "Susceptible -> Exposed {Hospitalized}",
      "entryState": "susceptible",
      "exitState": "exposed",
      "contactState": "hospitalized",
      "transmissibility": 1
    },
    {
      "id": "contactWithFuneral",
      "label": "Susceptible -> Exposed {Funeral}",
      "entryState": "susceptible",
      "exitState": "exposed",
      "contactState": "funeral",
      "transmissibility": 1
    }
  ],
  "transitions": [
    {
      "id": "exposed2infectious",
      "label": "Exposed->Infectious",
      "entryState": "exposed",
      "exitState": "infectious",
      "probability": 1,
      "dwellTime": {"fixed": 3}
    },
    {
      "id": "infectious2hospitalized",
      "label": "Infectious->Hospitalized",
      "entryState": "infectious",
      "exitState": "hospitalized",
      "probability": 0.1111,
      "dwellTime": {"fixed": 2}
    },
    {
      "id": "infectious2funeral",
      "label": "Infectious->Funeral",
      "entryState": "infectious",
      "exitState": "funeral",
      "probability": 0.6667,
      "dwellTime": {"fixed": 10}
    },
    {
      "id": "infectious2removed",
      "label": "Infectious->Removed",
      "entryState": "infectious",
      "exitState": "removed",
      "probability": 0.2222,
      "dwellTime": {"fixed": 12}
    },
    {
      "id": "hospitalized2funeral",
      "label": "Hospitalized->Funeral",
      "entryState": "hospitalized",
      "exitState": "funeral",
      "probability": 0.1111,
      "dwellTime": {"fixed": 15}
    },
    {
      "id": "hospitalized2removed",
      "label": "Hospitalized->Removed",
      "entryState": "hospitalized",
      "exitState": "removed",
      "probability": 0.8889,
      "dwellTime": {"fixed": 15}
    },
    {
      "id": "funeral2removed",
      "label": "Funeral->Removed",
      "entryState": "funeral",
      "exitState": "removed",
      "probability": 1,
      "dwellTime": {"fixed": 1}
    }
  ]
}
